server:
  type: default
  maxThreads: 50
  minThreads: 8
  applicationConnectors:
  - type: http
    port: 9001
  adminConnectors:
  - type: http
    port: 9002

database:
  driverClass: org.h2.Driver
  user: sa
  password:
  url: jdbc:h2:./target/payments;
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute